/**
 * Pre-computes the /cases gallery so page views never spend API calls.
 *
 *   npm run cases:build                          # analyze every case (leave-one-out)
 *   npm run cases:build -- --case rising-sun-rays
 *   npm run cases:build -- --generate            # also render Magic Hour alternatives
 *   npm run cases:build -- --generate --keep-analysis --case starbucks-korea   # re-render only
 *   npm run cases:build -- --generate --model gpt-image-2
 *
 * Writes src/data/cases/results/<slug>.json, downloads generated images to
 * public/cases/generated/, and regenerates src/data/cases/results/index.ts.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { ensureServerConditions, loadEnv } from "./lib/env";

const RESULTS_DIR = path.join("src", "data", "cases", "results");
const GENERATED_DIR = path.join("public", "cases", "generated");

function camel(slug: string): string {
  return slug.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase()).replace(/^([0-9])/, "_$1");
}

function writeIndex(): void {
  const slugs = readdirSync(RESULTS_DIR)
    .filter((f) => f.endsWith(".json"))
    .map((f) => f.replace(/\.json$/, ""))
    .sort();
  const lines = [
    "// Generated by scripts/build-cases.ts — do not edit by hand.",
    "// Each entry is a pre-computed gallery result, validated at read time.",
    "",
    ...slugs.map((s) => `import ${camel(s)} from "./${s}.json";`),
    ...(slugs.length ? [""] : []),
    `export const RAW_CASE_RESULTS: Record<string, unknown> = {${slugs.length ? "\n" + slugs.map((s) => `  "${s}": ${camel(s)},`).join("\n") + "\n" : ""}};`,
    "",
  ];
  writeFileSync(path.join(RESULTS_DIR, "index.ts"), lines.join("\n"));
}

async function main(): Promise<void> {
  if (ensureServerConditions()) return;
  loadEnv();

  const { CASES } = await import("../src/data/cases");
  const { analyzeCampaign } = await import("../src/lib/analyze");
  const { compileEditPrompt } = await import("../src/lib/compile-edit-prompt");
  const mh = await import("../src/lib/clients/magicHour");
  const { loadCreative } = await import("../src/lib/clients/creative");
  const { CaseResultSchema, MagicHourModelSchema } = await import("../src/lib/schema");

  const args = process.argv.slice(2);
  const only = args.includes("--case") ? args[args.indexOf("--case") + 1] : null;
  const generate = args.includes("--generate");
  // Re-render without re-analyzing. The analyzer is non-deterministic, so a rebuild just to attach
  // a Magic Hour render can quietly trade a good result for a worse one; this keeps the committed
  // analysis and redoes only the generation step.
  const keepAnalysis = args.includes("--keep-analysis");
  const model = MagicHourModelSchema.parse(args.includes("--model") ? args[args.indexOf("--model") + 1] : "flux-2-klein");

  mkdirSync(RESULTS_DIR, { recursive: true });
  const cases = only ? CASES.filter((c) => c.slug === only) : CASES;

  for (const c of cases) {
    console.log(`\n${c.slug}`);
    const existingPath = path.join(RESULTS_DIR, `${c.slug}.json`);
    let analysis;
    if (keepAnalysis) {
      if (!existsSync(existingPath)) throw new Error(`--keep-analysis needs an existing ${existingPath}`);
      analysis = CaseResultSchema.parse(JSON.parse(readFileSync(existingPath, "utf8"))).analysis;
      console.log("  reusing the committed analysis");
    } else {
      analysis = await analyzeCampaign(c.input, { excludeIncidentIds: c.ownIncidentIds, id: `case-${c.slug}` });
    }
    console.log(`  ${analysis.findings.length} findings: ${analysis.findings.map((f) => `${f.severity}/${f.category}/${f.locus.kind}`).join(", ") || "none"}`);

    let generation = null;
    const compiled = compileEditPrompt(analysis.findings, c.input);
    if (generate && compiled.prompt) {
      const creative = await loadCreative(c.input.imageUrl);
      const upload = await mh.getUploadUrl(creative.extension);
      await mh.uploadImage(upload.uploadUrl, creative.bytes, creative.mediaType);
      const job = await mh.editImage({ prompt: compiled.prompt, imageFilePaths: [upload.filePath], model, resolution: "1k", imageCount: 1, name: `Second Look case ${c.slug}` });
      console.log(`  Magic Hour project ${job.id}, ${job.creditsCharged} credits`);
      const done = await mh.pollUntilComplete(job.id, { onTick: (p, ms) => process.stdout.write(`\r  ${p.status} ${(ms / 1000).toFixed(0)}s   `) });
      process.stdout.write("\n");

      mkdirSync(GENERATED_DIR, { recursive: true });
      const images: string[] = [];
      for (const [i, d] of done.downloads.entries()) {
        const res = await fetch(d.url);
        if (!res.ok) throw new Error(`Download failed: HTTP ${res.status}`);
        const bytes = Buffer.from(await res.arrayBuffer());
        const ext = bytes[0] === 0x89 ? "png" : bytes[0] === 0xff ? "jpg" : "webp";
        const name = `${c.slug}-${i + 1}.${ext}`;
        writeFileSync(path.join(GENERATED_DIR, name), bytes);
        images.push(`/cases/generated/${name}`);
      }
      generation = {
        model,
        prompt: compiled.prompt,
        requestBody: { ...job.body, assets: { image_file_paths: ["api-assets/…"] } },
        creditsCharged: done.creditsCharged || job.creditsCharged,
        images,
        // Both kinds the render acted on: repairs to the image, and wording struck from the artwork.
        findingIds: [...compiled.addressed, ...compiled.printed].map((f) => f.id),
      };
    }

    const result = CaseResultSchema.parse({
      slug: c.slug,
      computedAt: new Date().toISOString(),
      leaveOneOut: true,
      analysis,
      generation,
    });
    writeFileSync(path.join(RESULTS_DIR, `${c.slug}.json`), JSON.stringify(result, null, 2));
    console.log(`  wrote ${path.join(RESULTS_DIR, `${c.slug}.json`)}`);
  }

  if (existsSync(RESULTS_DIR)) writeIndex();
  console.log("\nRegenerated src/data/cases/results/index.ts");
}

void main();
