// Generated by scripts/render-creative.ts — do not edit by hand.
// A content hash of each rendered creative. Appended to creative URLs so a
// redrawn image gets a new URL and no browser, image optimizer or CDN serves the old one.

export const CREATIVE_VERSIONS: Record<string, string> = {
  "control-cn-osmanthus-tea": "6f61125847",
  "control-kr-sweet-potato-latte": "623373fa2f",
  "control-mx-agua-fresca": "d773656eff",
  "green-hat": "eea3ee3e56",
  "pajero": "afbb3a0058",
  "rising-sun-rays": "88bcfcc3e9",
  "starbucks-korea": "fcac3adfbc",
  "vuela-en-cuero": "46d3df9c5c",
  "white-is-purity": "1192926c52",
};
